### GET /
GET http://localhost:5003

###To register a user /AUTH/REGISTER
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "maisha@gmail.com",
    "password": "123123123"
}


###Login in a user /AUTH/LOGIN
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "maisha@gmail.com",
    "password": "123123123"
}

### FETCH ALL TODOS GET/TODOS (protected)
GET http://localhost:5003/todos
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4NjI2MzY1LCJleHAiOjE3NDg3MTI3NjV9._DFNkTAmC9VOQSqFhr3sMx3u-YSESDNbpU7vInlUXts