### GET /
GET http://localhost:5003

###To register a user /AUTH/REGISTER
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "maisha@gmail.com",
    "password": "123123123"
}


###Login in a user /AUTH/LOGIN
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "maisha@gmail.com",
    "password": "123123123"
}

### FETCH ALL TODOS GET/TODOS (protected)
GET http://localhost:5003/todos
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4NjMzOTA1LCJleHAiOjE3NDg3MjAzMDV9.k4Mq4BBaA_Zhr29v7-osBa8_Cjo5afRRmjKKbo0TKbY

###Creates a new todo POST /TODOS (protected)
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4NjMzOTA1LCJleHAiOjE3NDg3MjAzMDV9.k4Mq4BBaA_Zhr29v7-osBa8_Cjo5afRRmjKKbo0TKbY
Content-Type: application/json

{
    "task": "Finish c-3 of backend course"
}

###Update a todo PUT /TODOS/:ID (protected)
PUT http://localhost:5003/todos/2?page=4
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4NjMzOTA1LCJleHAiOjE3NDg3MjAzMDV9.k4Mq4BBaA_Zhr29v7-osBa8_Cjo5afRRmjKKbo0TKbY
Content-Type: application/json

{
    "completed": 1
}

